### ISSUE TITLE
Finish data processing for sample bib files

### ISSUE THREAD

**Issue by karthik** [karthik/RRR#5]
assigned to @karthik

**Comment by danielturek** [comment]
I made one change just to remove the informative message.  It's a little faster now on the large files.

Do you suppose there's ever a concern with the max width of 500 (in read.fwf), perhaps with a long abstract?

My instinct is to create one more layer on top of your parsing, to abstract over the files being processed.  But since it seems we'll always only be doing R, R, and R, the current state is fine.

If this seems alright with you, please go ahead & close this issue.

**Comment by karthik** [comment]
> Do you suppose there's ever a concern with the max width of 500 (in read.fwf), perhaps with a long abstract?

Not really. The abstract breaks at 50 or so characters. So longer abstracts means longer lines. So the 500 per line is already quite high.
