### ISSUE TITLE
Pick only useful fields

### ISSUE THREAD

**Issue by karthik** [karthik/RRR#8]
Here is the full guide to fields: http://images.webofknowledge.com/WOK46/help/WOS/h_fieldtags.html

I think we only need 
AU - authors
TI - title
SO - publication name
DT - Doc type
AB - abstract
FU - funding agency

And everything else can go. Please comment if you feel otherwise, @danielturek

**Comment by karthik** [comment]
So both repeatibility and replicability are parsed. I need to parallelize reproducibility since it has far too many records.

This is what the parsed file looks like: https://github.com/karthik/RRR/blob/master/parsed/Repeatibility.csv

Thoughts before proceeding, @danielturek?

**Comment by danielturek** [comment]
For the record, it appears that:
Publication Type (PT) is used instead of Document Type (DT)
You able also included DOI number (DI)
Funding Agency (FU) was not available in the exported data.
Publication Year (PY) was added

So, our current parsed CSVs include:
PT Publication Type
AU Authors
TI Title
SO Publication Name
AB Abstract
DI DOI number
PY Publication Year

**Comment by danielturek** [comment]
I will also note the following fields are *theoretically* available:

**Comment by danielturek** [comment]
I also note the following fields are _theoretically_ available:

DE  Author Keywords
ID  Keywords Plus

There's a chance (?) I'd be able to negotiate download access to these, as well.  If so, we should include them.

Closing this issue for now.
